-- Tạo CSDL và sử dụng CSDL
CREATE DATABASE QL_TRAC_NGHIEM;
USE QL_TRAC_NGHIEM;

-- Tạo bảng và khóa chính
CREATE TABLE MON_HOC (
	MA_MON NVARCHAR(50) PRIMARY KEY,
	TEN_MON NVARCHAR(255),
);

CREATE TABLE TAI_KHOAN (
	MA_TK NVARCHAR(255) PRIMARY KEY,
	HO_TEN NVARCHAR(255),
	MAT_KHAU NVARCHAR(255),
	ROLE INT,
);

CREATE TABLE DE_THI (
	MA_DE_THI NVARCHAR(50) PRIMARY KEY,
	TEN_DE_THI NVARCHAR(255),
	MA_MON NVARCHAR(50),
	MA_TK NVARCHAR(255),
	THOI_LUONG INT,
	MAT_KHAU_DE NVARCHAR(255),
	TRANG_THAI INT,
);

CREATE TABLE CAU_HOI (
	MA_CAU_HOI NVARCHAR(50) PRIMARY KEY,
	MA_DE_THI NVARCHAR(50),
	NOI_DUNG NTEXT,
	PHUONG_AN_A NTEXT,
	PHUONG_AN_B NTEXT,
	PHUONG_AN_C NTEXT,
	PHUONG_AN_D NTEXT,
	DAP_AN NCHAR(1),
);

CREATE TABLE BAI_THI (
	MA_BAI_THI NVARCHAR(50) PRIMARY KEY,
	MA_DE_THI NVARCHAR(50),
	MA_TK NVARCHAR(255),
	THOI_GIAN_LAM SMALLDATETIME,
	DIEM FLOAT,
);

CREATE TABLE CHI_TIET_BAI_THI (
	MA_BAI_THI NVARCHAR(50),
	MA_CAU_HOI NVARCHAR(50),
	PHUONG_AN_CHON NCHAR(1),
	KET_QUA NVARCHAR(10),
	PRIMARY KEY (MA_BAI_THI, MA_CAU_HOI),
);

-- Tạo các ràng buộc khóa ngoại
ALTER TABLE DE_THI
ADD CONSTRAINT FK_DE_THI_MON_HOC
FOREIGN KEY (MA_MON) REFERENCES MON_HOC(MA_MON);

ALTER TABLE DE_THI
ADD CONSTRAINT FK_DE_THI_TAI_KHOAN
FOREIGN KEY (MA_TK) REFERENCES TAI_KHOAN(MA_TK);

ALTER TABLE CAU_HOI
ADD CONSTRAINT FK_CAU_HOI_DE_THI
FOREIGN KEY (MA_DE_THI) REFERENCES DE_THI(MA_DE_THI);

ALTER TABLE BAI_THI
ADD CONSTRAINT FK_BAI_THI_DE_THI
FOREIGN KEY (MA_DE_THI) REFERENCES DE_THI(MA_DE_THI);

ALTER TABLE BAI_THI
ADD CONSTRAINT FK_BAI_THI_TAI_KHOAN
FOREIGN KEY (MA_TK) REFERENCES TAI_KHOAN(MA_TK);

ALTER TABLE CHI_TIET_BAI_THI
ADD CONSTRAINT FK_CHI_TIET_BAI_THI_BAI_THI
FOREIGN KEY (MA_BAI_THI) REFERENCES BAI_THI(MA_BAI_THI);

ALTER TABLE CHI_TIET_BAI_THI
ADD CONSTRAINT FK_CHI_TIET_BAI_THI_CAU_HOI
FOREIGN KEY (MA_CAU_HOI) REFERENCES CAU_HOI(MA_CAU_HOI);

-- Nạp dữ liệu
INSERT INTO MON_HOC VALUES (N'TOAN', N'Toán');
INSERT INTO MON_HOC VALUES (N'VLY', N'Vật lý');
INSERT INTO MON_HOC VALUES (N'HHOC', N'Hóa học');
INSERT INTO MON_HOC VALUES (N'SHOC', N'Sinh học');
INSERT INTO MON_HOC VALUES (N'NVAN', N'Ngữ văn');
INSERT INTO MON_HOC VALUES (N'LSU', N'Lịch sử');
INSERT INTO MON_HOC VALUES (N'DLY', N'Địa lý');
INSERT INTO MON_HOC VALUES (N'TANH', N'Tiếng Anh');
INSERT INTO MON_HOC VALUES (N'THOC', N'Tin học');
INSERT INTO MON_HOC VALUES (N'GDKT-PL', N'Giáo dục kinh tế và pháp luật');

INSERT INTO TAI_KHOAN VALUES (N'admin', N'Admin', N'admin', 2);
INSERT INTO TAI_KHOAN VALUES (N'GV0001', N'Nguyễn Văn An', N'123456', 1);
INSERT INTO TAI_KHOAN VALUES (N'HS0001', N'Nguyễn Tuấn Anh', N'123456', 0);

-- SELECT dữ liệu
SELECT * FROM TAI_KHOAN;
SELECT * FROM MON_HOC;

SELECT * FROM DE_THI;
SELECT * FROM CAU_HOI;
SELECT * FROM BAI_THI;
SELECT * FROM CHI_TIET_BAI_THI;

-- TEST DATA
-- Insert a test into DE_THI (History Exam)
INSERT INTO DE_THI VALUES (N'LSU001', N'Kiểm tra Lịch Sử 15 phút', N'LSU', N'GV0001', 15, 'a', 1);

-- Insert questions into CAU_HOI
INSERT INTO CAU_HOI VALUES 
(N'LSUQ001', N'LSU001', N'Ai là người phát hiện ra châu Mỹ?', N'Columbus', N'Magellan', N'Vasco da Gama', N'James Cook', N'A'),
(N'LSUQ002', N'LSU001', N'Năm 1945, sự kiện lịch sử quan trọng nào diễn ra ở Việt Nam?', N'Chiến dịch Điện Biên Phủ', N'Cách mạng tháng Tám', N'Tuyên ngôn độc lập', N'Hiệp định Genève', N'C'),
(N'LSUQ003', N'LSU001', N'Nước nào là đồng minh của Việt Nam trong kháng chiến chống Mỹ?', N'Liên Xô', N'Anh', N'Pháp', N'Nhật Bản', N'A'),
(N'LSUQ004', N'LSU001', N'Nhà Nguyễn thành lập vào năm nào?', N'1802', N'1858', N'1945', N'1975', N'A'),
(N'LSUQ005', N'LSU001', N'Chiến dịch nào kết thúc cuộc kháng chiến chống thực dân Pháp?', N'Chiến dịch Hồ Chí Minh', N'Chiến dịch Tây Nguyên', N'Chiến dịch Biên giới', N'Chiến dịch Điện Biên Phủ', N'D');

-- Insert an exam attempt into BAI_THI
INSERT INTO BAI_THI VALUES (N'BT001', N'LSU001', N'a', GETDATE(), 8.0);

-- Insert student's answers into CHI_TIET_BAI_THI
INSERT INTO CHI_TIET_BAI_THI VALUES 
(N'BT001', N'LSUQ001', N'A', N'Đúng'),
(N'BT001', N'LSUQ002', N'C', N'Đúng'),
(N'BT001', N'LSUQ003', N'B', N'Sai'),
(N'BT001', N'LSUQ004', N'A', N'Đúng'),
(N'BT001', N'LSUQ005', N'D', N'Đúng');