-- Tạo CSDL và sử dụng CSDL
DROP DATABASE QL_TRAC_NGHIEM; -- DROP DATABASE (nếu cấu trúc chưa trùng khớp)
CREATE DATABASE QL_TRAC_NGHIEM;
USE QL_TRAC_NGHIEM;

-- Tạo bảng và khóa chính
CREATE TABLE MON_HOC (
	MA_MON NVARCHAR(50) NOT NULL PRIMARY KEY,
	TEN_MON NVARCHAR(255) NOT NULL,
);

CREATE TABLE TAI_KHOAN (
	MA_TK NVARCHAR(255) NOT NULL PRIMARY KEY,
	HO_TEN NVARCHAR(255) NOT NULL,
	MAT_KHAU NVARCHAR(255) NOT NULL,
	ROLE INT NOT NULL,
);

CREATE TABLE DE_THI (
	MA_DE_THI NVARCHAR(50) NOT NULL PRIMARY KEY,
	TEN_DE_THI NVARCHAR(255) NOT NULL,
	MA_MON NVARCHAR(50) NOT NULL,
	MA_TK NVARCHAR(255) NOT NULL,
	THOI_LUONG INT NOT NULL,
	MAT_KHAU_DE NVARCHAR(255),
	TRANG_THAI INT NOT NULL DEFAULT 1,
);

CREATE TABLE CAU_HOI (
	MA_CAU_HOI NVARCHAR(50) NOT NULL PRIMARY KEY,
	MA_DE_THI NVARCHAR(50) NOT NULL,
	LOAI_NOI_DUNG INT NOT NULL DEFAULT 0,
	NOI_DUNG NTEXT NOT NULL,
	PHUONG_AN_A NTEXT,
	PHUONG_AN_B NTEXT,
	PHUONG_AN_C NTEXT,
	PHUONG_AN_D NTEXT,
	DAP_AN NCHAR(1) NOT NULL,
);

CREATE TABLE BAI_THI (
	MA_BAI_THI NVARCHAR(50) NOT NULL PRIMARY KEY,
	MA_DE_THI NVARCHAR(50) NOT NULL,
	MA_TK NVARCHAR(255) NOT NULL,
	THOI_GIAN_LAM SMALLDATETIME NOT NULL,
	DIEM FLOAT,
);

CREATE TABLE CHI_TIET_BAI_THI (
	MA_BAI_THI NVARCHAR(50) NOT NULL,
	MA_CAU_HOI NVARCHAR(50) NOT NULL,
	PHUONG_AN_CHON NCHAR(1),
	KET_QUA NVARCHAR(10) NOT NULL,
	PRIMARY KEY (MA_BAI_THI, MA_CAU_HOI),
);

-- Tạo các ràng buộc khóa ngoại
ALTER TABLE DE_THI
ADD CONSTRAINT FK_DE_THI_MON_HOC
FOREIGN KEY (MA_MON) REFERENCES MON_HOC(MA_MON);

ALTER TABLE DE_THI
ADD CONSTRAINT FK_DE_THI_TAI_KHOAN
FOREIGN KEY (MA_TK) REFERENCES TAI_KHOAN(MA_TK);

ALTER TABLE CAU_HOI
ADD CONSTRAINT FK_CAU_HOI_DE_THI
FOREIGN KEY (MA_DE_THI) REFERENCES DE_THI(MA_DE_THI)
ON DELETE CASCADE;

ALTER TABLE BAI_THI
ADD CONSTRAINT FK_BAI_THI_DE_THI
FOREIGN KEY (MA_DE_THI) REFERENCES DE_THI(MA_DE_THI)
ON DELETE CASCADE;

ALTER TABLE BAI_THI
ADD CONSTRAINT FK_BAI_THI_TAI_KHOAN
FOREIGN KEY (MA_TK) REFERENCES TAI_KHOAN(MA_TK);

ALTER TABLE CHI_TIET_BAI_THI
ADD CONSTRAINT FK_CHI_TIET_BAI_THI_BAI_THI
FOREIGN KEY (MA_BAI_THI) REFERENCES BAI_THI(MA_BAI_THI)
ON DELETE CASCADE;

ALTER TABLE CHI_TIET_BAI_THI
ADD CONSTRAINT FK_CHI_TIET_BAI_THI_CAU_HOI
FOREIGN KEY (MA_CAU_HOI) REFERENCES CAU_HOI(MA_CAU_HOI);

-- Nạp dữ liệu
INSERT INTO MON_HOC VALUES (N'TOAN', N'Toán');
INSERT INTO MON_HOC VALUES (N'VLY', N'Vật lý');
INSERT INTO MON_HOC VALUES (N'HHOC', N'Hóa học');
INSERT INTO MON_HOC VALUES (N'SHOC', N'Sinh học');
INSERT INTO MON_HOC VALUES (N'NVAN', N'Ngữ văn');
INSERT INTO MON_HOC VALUES (N'LSU', N'Lịch sử');
INSERT INTO MON_HOC VALUES (N'DLY', N'Địa lý');
INSERT INTO MON_HOC VALUES (N'TANH', N'Tiếng Anh');
INSERT INTO MON_HOC VALUES (N'THOC', N'Tin học');
INSERT INTO MON_HOC VALUES (N'GDKT-PL', N'Giáo dục kinh tế và pháp luật');

-- Chỉ cần insert tài khoản Admin, các tài khoản khác dùng giao diện để tạo
INSERT INTO TAI_KHOAN VALUES (N'admin', N'Admin', N'admin', 2);
-- INSERT INTO TAI_KHOAN VALUES (N'GV0001', N'Nguyễn Văn An', N'123456', 1);
-- INSERT INTO TAI_KHOAN VALUES (N'HS0001', N'Nguyễn Tuấn Anh', N'123456', 0);

-- SELECT dữ liệu
SELECT * FROM TAI_KHOAN;
SELECT * FROM MON_HOC;
SELECT * FROM DE_THI;
SELECT * FROM CAU_HOI;
SELECT * FROM BAI_THI;
SELECT * FROM CHI_TIET_BAI_THI;
